### ISSUE TITLE
Add 'important comments' configuration in SASS

### ISSUE THREAD

**Issue by bagasnur** [mjeanroy/gulp-header-comment#449]
I have some ideas about adding an alternative configuration for 'important' block comments in SASS/SCSS. So when the SASS/SCSS file is compiled in `compressed` mode, the block comments will be included.

Current:
```
/**
  * Comment text
  */
```

Expect:
```
/*!
  * Important comment text
  */
```

**Comment by mjeanroy** [comment]
Hi @bagasnur,

I'm not sure to understand your request, could you elaborate a bit more? 🙂

**Comment by bagasnur** [comment]
Ok, for example: I would use gulp-header-comment to add important comments in the SCSS file like this:

``` scss
%sub-sup-default {
	font-size: 0.75rem;
	position: relative;
	vertical-align: baseline;
}
sup {
	@extend %sub-sup-default;
	top: -0.75em;
}
sub {
	@extend %sub-sup-default;
	bottom: -0.25em;
}
```

## Expect:
``` scss
/*!
 * This is important header comment for compressed mode
 */

%sub-sup-default {
	font-size: 0.75rem;
	position: relative;
	vertical-align: baseline;
}
sup {
	@extend %sub-sup-default;
	top: -0.75em;
}
sub {
	@extend %sub-sup-default;
	bottom: -0.25em;
}
```

So, when this file is compiled to CSS in `compressed` mode, the output will be like this:

``` css
/*!
 * This is header comment
 */

sub,sup{font-size:.75rem;position:relative;vertical-align:baseline}sup{top:-0.75em}sub{bottom:-0.25em}
```

https://sass-lang.com/documentation/syntax/comments

## Current:

``` scss
/**
 * This is not an important header comment for compressed mode
 */

%sub-sup-default {
	font-size: 0.75rem;
	position: relative;
	vertical-align: baseline;
}
sup {
	@extend %sub-sup-default;
	top: -0.75em;
}
sub {
	@extend %sub-sup-default;
	bottom: -0.25em;
}
```

Results in `compressed` mode, comments is not included like this:

``` css
sub,sup{font-size:.75rem;position:relative;vertical-align:baseline}sup{top:-0.75em}sub{bottom:-0.25em}
```
